# .github/workflows/preview.yml
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get PR branch
        id: pr_branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk 'BEGIN {FS="/"} {print $3}')"
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: ${{ steps.pr_branch.outputs.branch }}
          source-dir: .
          umbrella-dir: pr-preview
          action: auto